### ISSUE TITLE
How to improve LoD reading?

### ISSUE THREAD

**Issue by balazsdukai** [safesoftware/fme-CityJSON#53]
890f555 fixes #50 but not in very elegant way. See in the screenshot below of the result of reading a file that has a single object with LoD 1.2 . In this you see that only a single Building feature was created and 87 ignored, which is what I want.

![Screenshot_20200309_144914](https://user-images.githubusercontent.com/7190603/76219716-89dd3680-6216-11ea-83cf-53a574bfac4f.png)

However my problem is that, the `Feature type` is unknown, instead of reporting the CityObject types in the data (in this case it would be Building) that were not read.

I see that the reason for this lies in the way I implemented this (of course... :-) ). Here before a feature would be "populated" I check for its LoD and skip populating the feature if the conditions require so. Thus I increment the nextObject iterator and return from the `read` method before the feature type etc. would be set --> unknown feature types.

https://github.com/safesoftware/fme-CityJSON/blob/890f555b8362f8af2d306c0eef2907562b65a28b/fmecityjson/fmecityjsonreader.cpp#L399-L430

I tried doing the LoD check above *after* setting the feature type but in that case a feature is created from each object, essentially resulting in #50 again.

What I would like to achieve is the same behavior as we have when we select certain types from the available Feature types for reading (see screenshot below). But in this case we would read only some from a given type and ignore the rest (by setting the LoD parameter). So to go back to the first screenshot, the Unexpected Input dialog would report 87 Building features, instead of 87 unknown features. Would that be possible @KevinWiebe :grimacing: ?

![image](https://user-images.githubusercontent.com/7190603/76222156-7af88300-621a-11ea-8b3e-29f9c4c9fc69.png)

**Comment by KevinWiebe** [comment]
I think I understand your circumstance here, Balazs.
But I think FME works a bit differently than you expect.

That "Unexpected Input" dialog box pops up when the reader produces a feature with a FeatureType that does no match any of the reader schemas present on the Workbench canvas.  It is kind of like saying there is an error in workbench.  Normally people will have a Reader Schema present for all FeatureTypes, and just not hook up the ones they wish to ignore.

In your case, you are asking if you can send features out of the reader with the same FeatureType, but have some pop up in this "unexpected input" dialog box, and some not.  Unfortunately you can't.  If your reader produces features with a "Building" feature type, and you have the Building reader schema present in workbench, then none of them will be dropped.


Instead, what we normally do in other readers, with this same issue, is just not have the reader produce any features at all for the things it is being asked to ignore.  Do not return from the "read()" method with any feature set up with information from things being asked to ignore.

The easiest way I can see to do this, would be to change line 421, in your code snip above.  Instead of 
`          return FME_SUCCESS; `
maybe try this:
`          return read(feature, endOfFile); `

This will just recursively call the read function again to get a good feature.
(Another way would be to put a loop around the whole bunch of code in the read() method, and keep looping until you've got a feature that you don't want to skip.)

Does this make sense?  Does this satisfy what you are asking?
If you agree and can tweak your pull request #49 feel free to merge that in yourself.
Thanks, @balazsdukai 
cc @hugoledoux
